server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mawredy_database
    username: root
    password: 5aL3d&hesham2023&&
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    enabled: true



